// This file is generated by RustQ. Do not edit by hand.

#[derive(Clone, Debug, rustler::NifMap)]
pub struct Diagnostic {
    pub rule: String,
    pub message: String,
    pub severity: Atom,
    pub labels: Vec<(u32, u32, Option<String>)>,
    pub help: Option<String>,
    pub fixes: Vec<(u32, u32, String)>,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct LintInput {
    pub plugins: Vec<String>,
    pub rules: Vec<(String, String)>,
    pub envs: Vec<(String, bool)>,
    pub globals: Vec<(String, String)>,
    pub fix: bool,
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct ParseError {
    pub message: String,
    pub labels: Vec<(u32, u32, Option<String>)>,
    pub help: Option<String>,
}
