// This file is generated by RustQ. Do not edit by hand.

#[rustler::nif(schedule = "DirtyCpu")]
fn lint<'a>(
    env: Env<'a>,
    source_term: Term<'a>,
    filename: &str,
    input: LintInput,
) -> NifResult<Term<'a>> {
    lint_impl(env, source_term, filename, input)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn type_aware_rules(
    plugins: Vec<String>,
    rules: Vec<(String, RuleSeverity)>,
) -> NifResult<Result<Vec<(String, RuleSeverity)>, String>> {
    type_aware_rules_impl(plugins, rules)
}
