// This file is generated by RustQ. Do not edit by hand.

#[rustler::nif(schedule = "DirtyCpu")]
fn lint<'a>(
    env: Env<'a>,
    source_term: Term<'a>,
    filename: &str,
    plugins: Vec<String>,
    rules: Vec<(String, String)>,
    fix: bool,
) -> NifResult<Term<'a>> {
    lint_impl(env, source_term, filename, plugins, rules, fix)
}
