// This file is generated by RustQ. Do not edit by hand.

#[rustler::nif(schedule = "DirtyCpu")]
fn lint<'a>(
    env: Env<'a>,
    source_term: Term<'a>,
    filename: &str,
    input: LintInput,
) -> NifResult<Term<'a>> {
    lint_impl(env, source_term, filename, input)
}
