// This file is generated by RustQ. Do not edit by hand.

rustler::atoms! {
    alternate, argument, arguments, array_expression, array_pattern,
    arrow_function_expression, assignment_expression, assignment_pattern, async_field =
    "async", await_expression, await_field = "await", big_int_literal, bigint,
    binary_expression, block, block_statement, body, boolean_literal, break_statement,
    call_expression, callee, cases, chain_expression, class_declaration,
    class_expression, computed, computed_member_expression, conditional_expression,
    consequent, continue_statement, cooked, debugger_statement, declaration,
    declarations, delegate, discriminant, do_while_statement, elements, empty_statement,
    export_all_declaration, export_default_declaration, export_named_declaration,
    exported, expression, expression_statement, expressions, finalizer, flags,
    for_in_statement, for_of_statement, for_statement, function_declaration,
    function_expression, generator, handler, id, identifier, identifier_reference,
    if_statement, import_declaration, import_default_specifier, import_expression,
    import_namespace_specifier, import_specifier, imported, init, key, kind, label,
    labeled_statement, left, literal, local, logical_expression, member_expression, meta,
    meta_property, method, method_definition, name, new_expression, null_literal,
    numeric_literal, object, object_expression, object_pattern, operator, optional,
    param, params, parenthesized_expression, pattern, prefix, properties, property,
    property_definition, quasi, quasis, raw, reg_exp_literal, regex, rest_element,
    return_statement, right, sequence_expression, shorthand, source, specifiers,
    spread_element, static_block, static_field = "static", static_member_expression,
    string_literal, super_class = "superClass", super_expr = "super", switch_statement,
    tag, tagged_template_expression, tail, template_literal, test, this_expression,
    throw_statement, try_statement, unary_expression, update, update_expression, value,
    variable_declaration, while_statement, with_statement, yield_expression,
}
