// This file is generated by RustQ. Do not edit by hand.

fn get<'a>(term: Term<'a>, key: rustler::Atom) -> Option<Term<'a>> {
    term.map_get(key).ok()
}
fn is_nil<'a>(term: Term<'a>) -> bool {
    if term.is_atom() {
        match term.atom_to_string() {
            Ok(value) => value == "nil",
            Err(_reason) => false,
        }
    } else {
        false
    }
}
fn opt<'a>(term: Term<'a>, key: rustler::Atom) -> Option<Term<'a>> {
    match get(term, key) {
        Some(value) => if is_nil(value) { None } else { Some(value) }
        None => None,
    }
}
fn str_val<'a>(term: Term<'a>, key: rustler::Atom) -> String {
    match get(term, key) {
        Some(value) => {
            match value.decode::<String>() {
                Ok(decoded) => decoded,
                Err(_reason) => value.atom_to_string().unwrap_or_default(),
            }
        }
        None => String::new(),
    }
}
fn bool_val<'a>(term: Term<'a>, key: rustler::Atom) -> bool {
    match get(term, key) {
        Some(value) => value.decode().unwrap_or_default(),
        None => false,
    }
}
fn f64_val<'a>(term: Term<'a>, key: rustler::Atom) -> f64 {
    match get(term, key) {
        Some(value) => {
            match value.decode::<f64>() {
                Ok(decoded) => decoded,
                Err(_reason) => {
                    match value.decode::<i64>() {
                        Ok(decoded) => decoded as f64,
                        Err(_reason) => 0.0,
                    }
                }
            }
        }
        None => 0.0,
    }
}
fn list_val<'a>(term: Term<'a>, key: rustler::Atom) -> Vec<Term<'a>> {
    match get(term, key) {
        Some(value) => value.decode().unwrap_or_default(),
        None => Vec::new(),
    }
}
fn type_atom<'a>(term: Term<'a>) -> Option<rustler::Atom> {
    match get(term, atoms::r#type()) {
        Some(value) => value.decode::<rustler::Atom>().ok(),
        None => None,
    }
}
fn type_eq<'a>(term: Term<'a>, expected: rustler::Atom) -> bool {
    type_atom(term) == Some(expected)
}
fn type_str<'a>(term: Term<'a>) -> String {
    match get(term, atoms::r#type()) {
        Some(value) => {
            match value.atom_to_string() {
                Ok(decoded) => decoded,
                Err(_reason) => String::from("<no type>"),
            }
        }
        None => String::from("<no type>"),
    }
}
