// This file is generated by RustQ. Do not edit by hand.

#[rustler::nif(schedule = "DirtyCpu")]
fn parse<'a>(
    env: Env<'a>,
    source_term: Term<'a>,
    filename: &str,
) -> NifResult<Term<'a>> {
    parse_impl(env, source_term, filename)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn valid(source_term: Term<'_>, filename: &str) -> NifResult<bool> {
    valid_impl(source_term, filename)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn transform<'a>(
    env: Env<'a>,
    source_term: Term<'a>,
    filename: &str,
    opts_term: Term<'a>,
) -> NifResult<Term<'a>> {
    transform_impl(env, source_term, filename, opts_term)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn minify<'a>(
    env: Env<'a>,
    source_term: Term<'a>,
    filename: &str,
    opts_term: Term<'a>,
) -> NifResult<Term<'a>> {
    minify_impl(env, source_term, filename, opts_term)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn bundle<'a>(
    env: Env<'a>,
    files: Vec<(String, Term<'a>)>,
    opts_term: Term<'a>,
) -> NifResult<Term<'a>> {
    bundle_impl(env, files, opts_term)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn bundle_entry<'a>(
    env: Env<'a>,
    entry: String,
    opts_term: Term<'a>,
) -> NifResult<Term<'a>> {
    bundle_entry_impl(env, entry, opts_term)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn bundle_run<'a>(env: Env<'a>, opts_term: Term<'a>) -> NifResult<Term<'a>> {
    bundle_run_impl(env, opts_term)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn select<'a>(
    env: Env<'a>,
    source_term: Term<'a>,
    filename: &str,
    spec: Term<'a>,
) -> NifResult<Term<'a>> {
    select_impl(env, source_term, filename, spec)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn transform_many<'a>(
    env: Env<'a>,
    inputs: Vec<(Term<'a>, String)>,
    opts_term: Term<'a>,
) -> NifResult<Term<'a>> {
    transform_many_impl(env, inputs, opts_term)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn codegen<'a>(env: Env<'a>, ast: Term<'a>) -> NifResult<Term<'a>> {
    codegen_impl(env, ast)
}
