// This file is generated by RustQ. Do not edit by hand.

mod atoms {
    rustler::atoms! {
        ok, error, print_width, tab_width, use_tabs, semi, single_quote,
        jsx_single_quote, trailing_comma, bracket_spacing, bracket_same_line,
        arrow_parens, end_of_line, quote_props, single_attribute_per_line, object_wrap,
        experimental_operator_position, experimental_ternaries,
        embedded_language_formatting, sort_imports, sort_tailwindcss, ignore_case,
        sort_side_effects, order, newlines_between, partition_by_newline,
        partition_by_comment, internal_pattern, config, stylesheet, functions,
        attributes, preserve_whitespace, preserve_duplicates
    }
}
