// This file is generated by RustQ. Do not edit by hand.

fn get<'a>(term: Term<'a>, key: rustler::Atom) -> Option<Term<'a>> {
    term.map_get(key).ok()
}
fn get_bool<'a>(term: Term<'a>, key: rustler::Atom) -> Option<bool> {
    match get(term, key) {
        Some(value) => value.decode::<bool>().ok(),
        None => None,
    }
}
fn get_i64<'a>(term: Term<'a>, key: rustler::Atom) -> Option<i64> {
    match get(term, key) {
        Some(value) => value.decode::<i64>().ok(),
        None => None,
    }
}
fn get_string<'a>(term: Term<'a>, key: rustler::Atom) -> Option<String> {
    match get(term, key) {
        Some(value) => {
            match value.decode::<String>() {
                Ok(decoded) => Some(decoded),
                Err(_reason) => value.atom_to_string().ok(),
            }
        }
        None => None,
    }
}
fn get_string_list<'a>(term: Term<'a>, key: rustler::Atom) -> Option<Vec<String>> {
    match get(term, key) {
        Some(value) => value.decode::<Vec<String>>().ok(),
        None => None,
    }
}
fn get_map<'a>(term: Term<'a>, key: rustler::Atom) -> Option<Term<'a>> {
    match get(term, key) {
        Some(value) => if value.is_map() { Some(value) } else { None }
        None => None,
    }
}
