// This file is generated by RustQ. Do not edit by hand.

#[rustler::nif(schedule = "DirtyCpu")]
fn format<'a>(
    env: Env<'a>,
    source_term: Term<'a>,
    filename: &str,
    opts: Term<'a>,
) -> NifResult<Term<'a>> {
    format_impl(env, source_term, filename, opts)
}
